### ISSUE TITLE
Socket connection doesn't authenticate after refresh

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#1130]
(that's what it looks like, at least.)

After a refresh, wait for 30 ish seconds, and you'll see yourself leave the room.

**Comment by lilbennyboi** [comment]
Hey, i can work on fixing this if you add me as a contributor, i'd love to help out.

**Comment by goto-bus-stop** [comment]
I hadn't been able to reproduce this for a while and I haven't heard complaints from EDM Spot yet so this might actually be fixed 🙏🏻 


e; closing this to clean up the issue list. can reopen if it does happen again.

**Comment by goto-bus-stop** [comment]
Still happening in EDM Spot after all! When I refresh the page there, sometimes the web client doesn't send the socket token.
