### ISSUE TITLE
Crash when starting a search

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#1309]
The `PlaylistManagerPanel` container `connect()` function is ran when starting a search, even though the current playlist has already been deselected, and that container should be unmounted.

This looks similar, though I don't think our issue is triggered from `componentDidUpdate`: https://github.com/reduxjs/react-redux/issues/1397
will need some investigation and possibly a react-redux fix.

**Comment by lukas1994** [comment]
Having a similar issue with my project. Does rewriting everything to use hooks actually help?

**Comment by goto-bus-stop** [comment]
@lukas1994 I think the issue was already fixed for me by only converting the affected container and its parent. This is just a project where I like rewriting everything all the time :slightly_smiling_face:
