### ISSUE TITLE
Quick scrolling in the playlist panel causes multiple requests for the same page

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#1709]
If you scroll quickly, the `onRequestPage` function gets called many times for the same page, and we send off multiple requests for the same data. There should be some check in there so we only load the data for each page once.

**Comment by goto-bus-stop** [comment]
I think a possible way to address this is by keeping a list of in-flight page requests in the BaseMediaList component. It's a bit of a chore doing it manually but should work at least.

https://github.com/u-wave/web/blob/109861842cac924ee62bb8616d3b1f593809844c/src/components/MediaList/BaseMediaList.js#L116-L119

If we add a state variable or ref for in-flight page requests to the `BaseMediaList` component, `loadMoreItems` can do something like:
```js
const page = Math.floor(start / 50);
if (!inFlightPageRequests.has(page)) {
  inFlightPageRequests.add(page)
  onRequestPage(page).finally(() => {
    inFlightPageRequests.delete(page)
  });
}
```

**Comment by uriell** [comment]
Hi, Burkes here.

I noticed these props on the library used for infinite scrolling, but they didn't seem to help at all.
<img width="726" alt="image" src="https://user-images.githubusercontent.com/39530115/108648512-3224f300-749a-11eb-951c-4998c9e43dd5.png">

Anyways, more info on my PR, open to suggestions.
