### ISSUE TITLE
SourceNotFoundError: Source "youtube" not found.

### ISSUE THREAD

**Issue by temikael** [u-wave/web#1836]
Hi,

I installed üWave and all the dependencies on my Ubuntu 20.04.1 server.
I ran the core with the _npm start_ command, and the web client with the _npm run prod && npm run serve_ command.

I signed in my test user, then I created my first playlist.
But when I searched a YouTube video via the search bar, the message **Source "youtube" not found** displayed.

Furthermore, when I checked the terminal, I received this log:

```
  uwave:http:error SourceNotFoundError: Source "youtube" not found.
  uwave:http:error     at new NotFoundError (/home/test/uwave/u-wave-core/src/errors/index.js:83:7)
  uwave:http:error     at search (/home/test/uwave/u-wave-core/src/controllers/search.js:58:11)
  uwave:http:error     at /home/test/uwave/u-wave-core/src/route.js:5:21
  uwave:http:error     at Layer.handle [as handle_request] (/home/test/uwave/u-wave-core/node_modules/router/lib/layer.js:93:5)
  uwave:http:error     at next (/home/test/uwave/u-wave-core/node_modules/router/lib/route.js:144:13)
  uwave:http:error     at Route.dispatch (/home/test/uwave/u-wave-core/node_modules/router/lib/route.js:109:3)
  uwave:http:error     at handle (/home/test/uwave/u-wave-core/node_modules/router/index.js:526:11)
  uwave:http:error     at Layer.handle [as handle_request] (/home/test/uwave/u-wave-core/node_modules/router/lib/layer.js:93:5)
  uwave:http:error     at /home/test/uwave/u-wave-core/node_modules/router/index.js:296:22
  uwave:http:error     at param (/home/test/uwave/u-wave-core/node_modules/router/index.js:379:14)
  uwave:http:error     at param (/home/test/uwave/u-wave-core/node_modules/router/index.js:390:14)
  uwave:http:error     at Function.process_params (/home/test/uwave/u-wave-core/node_modules/router/index.js:435:3)
  uwave:http:error     at next (/home/test/uwave/u-wave-core/node_modules/router/index.js:290:10)
  uwave:http:error     at middleware.then (/home/test/uwave/u-wave-core/src/utils/wrapMiddleware.js:9:19)
  uwave:http:error     at process._tickCallback (internal/process/next_tick.js:68:7) +59s
```

Can you tell me how I can resolve this error, please?

Best regards,

temikael

**Comment by goto-bus-stop** [comment]
`npm start` in the core repo runs the [development server](https://github.com/u-wave/core/blob/734880b599f9a6433ce6368d0b1cc57753da7354/dev/u-wave-dev-server). It adds the youtube and soundcloud sources depending on environment variables. So "youtube" is only available if the `YOUTUBE_API_KEY` environment variable is set:
```
YOUTUBE_API_KEY=yourkeyhere npm start
```
You can also put a `.env` file in the core repository root, then `npm start` will pick it up automatically.
```
YOUTUBE_API_KEY=yourkeyhere
```

(The web client does not yet know about server-side configuration of media sources, that's why it always shows them even if the keys are missing.)

**Comment by temikael** [comment]
I put my `YOUTUBE_API_KEY` into the .env file and it works!
Thanks for the tip :)
