### ISSUE TITLE
Current song duration timer label

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#187]
Currently it's not possible to find out exactly how long the current song is playing for and how long it has to go.

I suspect adding a timer somewhere where it's always visible will push the UI just about into "cluttered" territory. An alternate solution would be to add a tooltip to the Progress bar, where if you hover it, it shows the current elapsed time and the total duration of the current song, like "1:23 / 2:34".

**Comment by goto-bus-stop** [comment]
haven't actually felt like I needed this over the past few years, so probably unnecessary. We could come back to this if someone does want the feature.

**Comment by fawaf** [comment]
> I suspect adding a timer somewhere where it's always visible will push the UI just about into "cluttered" territory. An alternate solution would be to add a tooltip to the Progress bar, where if you hover it, it shows the current elapsed time and the total duration of the current song, like "1:23 / 2:34".

i like the tooltip/hover part. agreed with no need to "clutter" up the UI more.
