### ISSUE TITLE
in search results, show playlist names that the media is already in

### ISSUE THREAD

**Issue by goto-bus-stop** [u-wave/web#371]
So that you don't have to check manually. ~Oldplug~ Old plug.dj extensions did this and it was pretty useful, for us especially because üWave allows multiple items for the same source media in the same playlist.

Needs some api-v1 additions though.

**Comment by goto-bus-stop** [comment]
Depends u-wave/core#85 kinda

**Comment by goto-bus-stop** [comment]
üWave Core 0.5 will have the functionality for this; we just need some UI.

**Comment by goto-bus-stop** [comment]
A different idea: when you drop an item on a playlist, and that item is already in the playlist, you get a confirmation popup. It shows the existing duplicate items, and lets you decline, go through anyway, or edit the media before adding it (would be handy combined with https://github.com/u-wave/web/pull/1677).

**Comment by pledi** [comment]
this is a good idea, I do have unwanted duplicates because of this sometimes

**Comment by goto-bus-stop** [comment]
I think the confirmation popup is still a good idea, maybe even for all additions, to incentivise fixing tags before adding…but it might be too much friction. we now show playlists media is in so this one can be closed \ :smile: /
