### ISSUE TITLE
ui hangs if import fails for any reason

### ISSUE THREAD

**Issue by gnowxilef** [u-wave/web#647]
even minimizing the menu does not fix it. a full page refresh is needed to get rid of the spinner.

**Comment by goto-bus-stop** [comment]
there is a close button in the top right:

![](http://i.imgur.com/MW6SWqZ.png)

but indeed, it shouldn't hang, but probably just return to the main import screen if something fails

**Comment by goto-bus-stop** [comment]
Fixed in #674, it will now return to the main import screen when an error occurs. Thanks!
